kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: opspvc
  namespace: kube-ops
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 50Gi
